---
name: Conditional Statements
locale: en
type: learning
beta: false
teacher_info: ''
language: python3
id_format: "%05d"
order:
- 13
- 14
- 1
- 3
- 4
- 5
- 6
- 7
- 15
- 8
- 9
- 10
- 11
- 12
private: true
